### ISSUE TITLE
install Journal outside evolve (Arch)

### ISSUE THREAD

**Issue by greendragon2010** [evolve-os/journal#51] opened 2015-03-22 21:03 UTC
I have the following error when I install journal: 
(process:30404): GLib-GIO-ERROR **: Settings schema 'com.evolve-os.journal' is not installed

But once I installed Budgie it fixed the issue.

**Comment by zesterer** [comment] 2015-03-23 18:14
Yeah... @ryanleesipes you should probably make journal independent from Budgie with regards to GLib.Settings if you want to truly make Journal platform-agnostic.

**Comment by greendragon2010** [comment] 2015-03-25 16:18
I am working on a patch to check and see if com.evolve-os.journal exist in gsettings and if it doesn't created it so journal can run independent of Budgie. Any help will be appreciated since I've never used vala before.

**Comment by ikeydoherty** [comment] 2015-03-25 16:29
This has nothing to do with Budgie.. You need to recompile your schemas after install.

@zesterer given this is in evolve-os whats the harm in using evolveos schemas??

@greendragon2010 sudo glib-compile-schemas /usr/share/glib-2.0/schemas

**Comment by greendragon2010** [comment] 2015-03-25 16:38
When I installed the package from on Arch from the aur that was the error I got.

My plan to fix this is to still use "com.evolve-os.journal" as the scheme since it is a evolve os project. I also know someone who had s schema issue to when they install journal from the aur but it was a slightly different error.  I'm just trying to make sure the application will create the scheme if doesn't exist, so that it can be install on any distro with any desktop environment.  

@ikeydoherty so I could have just done that after I installed the aur package, and that would have fixed the issue?

**Comment by ikeydoherty** [comment] 2015-03-25 16:40
@greendragon2010  yup. So a package like budgie-desktop automatically does this post-install,however Journal does not, and that's where the issue is. So when you installed budgie, it recompiled all the schemas, including Journal's :)

**Comment by greendragon2010** [comment] 2015-03-25 16:42
@ikeydoherty  could we make Journal do this so it is not an issue, or could we have a pop up and ask the user to do it if the scheme doesn't exist? Just playing with ideas.

**Comment by ikeydoherty** [comment] 2015-03-25 16:45
@greendragon2010 problem is if the scheme doesn't exist, it will die. This is technically the correct behaviour. So it needs to either be corrected within the packaging, or within the package.

Now, when you have binary packages (outside of AUR) - a package has post installs to achieve this. i.e. its not done at build time. It should only be done on a non DESTDIR make install.

I'm not familiar enough with CMake (because I can't stand it) to be of help here, but I'm sure there are examples around of cmake gsettings integration.

**Comment by greendragon2010** [comment] 2015-03-25 16:49
Okay, I will look into cmake and see if I can figure it out. I have professor that understands cmake and make since he teaches C. I'll ask him if he knows or knows resources I can use to figure it out.

**Comment by greendragon2010** [comment] 2015-03-25 19:21
I believe this can be closed. If you follow the instruction to build and install then it will create the schemas for you. So people packaging this for other distros need to make sure this happens, and we can call this a packaging issue and not an application issue.

**Comment by ryanleesipes** [comment] 2015-03-25 19:40
@greendragon2010 great work, yeah, looks like Justin may need to take a look at this, as I think he may maintain the Arch package.

**Comment by Justinzobel** [comment] 2015-03-25 19:41
This is my bad. I made the AUR package. Will fix up asap

**Comment by ryanleesipes** [comment] 2015-03-25 21:32
@Justinzobel would you like me to assign this bug to you, so you can close it when you are done?

**Comment by ryanleesipes** [comment] 2015-03-25 21:33
Eh, nevermind, I can't assign it to you @Justinzobel - @ikeydoherty can Justin be included in the org?

**Comment by ryanleesipes** [comment] 2015-03-25 21:37
There we go :)

**Comment by Justinzobel** [comment] 2015-03-26 01:48
@greendragon2010 closing this off as i've updated the AUR install file, please re-open if it's not resolved.

**Closed by Justinzobel** 2015-03-26 01:48 UTC

**Comment by Justinzobel** [comment] 2015-03-26 01:55
Just confirmed this working from an Arch live ISO without budgie.

**Comment by greendragon2010** [comment] 2015-03-26 01:59
I believe the issue is fixed, just tested in a systemd container.
